version: "3.9"

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - .:/var/www/html
    depends_on:
      - database-container
    ports:
      - 3000:80 

  database-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: user
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - database-container
    ports:
      - "3001:80"
    environment:
      PMA_HOST: database-container 
      MYSQL_ROOT_PASSWORD: 123